### ISSUE TITLE
Unable to find moxa device

### ISSUE THREAD

**Issue by Duncik** [ankohanse/hass-studer-xcom#14]
Stucked on popup : "Searching Xcom Moxa Web Config"

Homeassistant generates theese faults everytime i try to configure this integration. 

2024-12-20 22:17:41.211 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection (None)
2024-12-20 22:17:41.211 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection (None)
2024-12-20 22:20:34.226 ERROR (MainThread) [habluetooth.scanner] hci0 (2C:CF:67:79:C8:89): Error stopping scanner: [org.bluez.Error.Failed] No discovery started
2024-12-20 22:22:25.873 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection (None)

**Comment by ankohanse** [comment]
Thanks for reporting this. I will try to reproduce and investigate what could cause this behavior.

Note: the third line im the errors seems unrelated, when searching for Xcom moxa web config we do not use bluetooth. Could possibly be conflicting components though...

**Comment by Duncik** [comment]
If there is anything i can do to replicate/log  feel free to write :-)
inwill do what i can.

**Comment by ankohanse** [comment]
Managed to reproduce and fix the 'unclosed connection' errors. Solution is released as v2024.12.4 just now.

However, this might not yet resolve your issue on being stuck in the "Searching Xcom Moxa Web Config" task.
Would you be able to perform the following steps?

1. If not already done, update the integration to v2024.12.4.
2. Enable debug logging for the studer integration by adding the following lines in configuration.yaml:
```
# logging
logger:
  default: info
  logs:
    custom_components.studer_xcom: debug
```

3. Restart Home Assistant
4. Under 'Settings->Integrations', add and configure the Studer intgration (if integration not yet there), or choose 'Reconfigure' in the integration if it is aleady there. Follow the steps to (re-)configure the integration until it finishes or until it seems to get stuck.
5. Under 'Settings->System->Logs', choose 'show full logs' and then 'download logs'. Add the logs to this bug report.

Filtered for relevant lines the log should look similar to:
```
[36m2024-12-23 14:19:18.951 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - create task xcom_webconfig, phase=MOXA_DISCOVER, idx=0[0m
[32m2024-12-23 14:19:18.952 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discover Xcom Moxa Web Config[0m
[36m2024-12-23 14:19:20.618 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet[0m
[36m2024-12-23 14:19:20.618 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0[0m
[32m2024-12-23 14:19:20.622 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.88.250[0m
[32m2024-12-23 14:19:20.624 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.127.254[0m
[32m2024-12-23 14:19:20.626 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.88.217[0m
[32m2024-12-23 14:19:20.628 INFO (MainThread) [aioxcom.xcom_discover] trying http://...    <repeated many more times>
[32m2024-12-23 14:19:20.817 INFO (MainThread) [aioxcom.xcom_discover] Found Moxa Web Config url: http://192.168.88.250[0m
[32m2024-12-23 14:19:20.826 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discovered Xcom Moxa Web Config at http://192.168.88.250[0m
[36m2024-12-23 14:19:20.826 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet[0m
[36m2024-12-23 14:19:20.826 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0[0m
[36m2024-12-23 14:19:20.831 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig done[0m
[36m2024-12-23 14:19:20.832 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - done, phase=MOXA_DISCOVER[0m
[36m2024-12-23 14:19:20.870 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step client - show form[0m
[36m2024-12-23 14:19:22.176 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step client - handle input {'voltage': '240_vac', 'port': 4001}[0m
```

**Comment by Duncik** [comment]
Thank you so much for quick response ! 
Here is the log : 
----------------------------------------------------------------------------
Studer Xcom
Domain: studer_xcom
----------------------------------------------------------------------------
2024-12-23 07:13:52.220 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - create task xcom_webconfig, phase=MOXA_DISCOVER, idx=0
2024-12-23 07:13:52.221 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discover Xcom Moxa Web Config
2024-12-23 07:13:52.337 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet
2024-12-23 07:13:52.337 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0
2024-12-23 07:13:52.338 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.127.254
2024-12-23 07:13:52.339 INFO (MainThread) [aioxcom.xcom_discover] trying http://172.30.232.2
2024-12-23 07:13:52.340 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.46
2024-12-23 07:13:52.340 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.10
2024-12-23 07:13:52.341 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.22
2024-12-23 07:13:52.341 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.12
2024-12-23 07:13:52.342 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.1
2024-12-23 07:13:52.344 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.33
2024-12-23 07:13:52.345 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.40
2024-12-23 07:13:52.345 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.38
2024-12-23 07:13:52.346 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.2
2024-12-23 07:13:52.362 INFO (MainThread) [aioxcom.xcom_discover] Found Moxa Web Config url: http://192.168.1.10
2024-12-23 07:13:52.363 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discovered Xcom Moxa Web Config at http://192.168.1.10
2024-12-23 07:13:52.363 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet
2024-12-23 07:13:52.363 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0
2024-12-23 07:13:52.363 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig done
2024-12-23 07:13:52.363 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - done, phase=MOXA_DISCOVER



Found correct IP but as i compare with yours logs i am missing last two entries. 
There is still same popup on frontend : "Searching Xcom Moxa Web Config"

**Comment by ankohanse** [comment]
Glad the unclosed connection error is indeed gone. Only one problem left to solve...

The order of popups has changed about 2 months ago so that I can provide better information during the voltage+port step. Order now is:
1. Discover moxa web config (automatic step, no user interaction)
2. Configure voltage + port (and display link to the moxa web config so user can easily check the port)
3. Discover Xcom devices (automatic step, no user interaction)
4. Display discovered devices and associated param and info numbers (and allow user to modify numbers)
5. Apply devices and numbers

So your traces start as I expect them to be. Just a bit of a mystery why the voltage+port step doesn't show itself. That step should always follow the last trace you see, no deviations possible in the code and should have a trace as first thing it does.
I'll keep investigating...

**Comment by ankohanse** [comment]
Have not been successful in replicating the issue or identifying a possible cause. I've removed the integration followed by a fresh install and also did a re-configure. Both times the expected forms for all steps were displayed correctly,
Also played around with deliberately messing up previously stored data to see if that would trigger the issue.

To help me figure out what makes your system different from mine could you tell me:

1. How did you add the integration, via HACS or via a manual copy of the files?
2. Does the issue currently occur during a fresh add of the integration, or are you trying to do a reconfigure of the integration?
3. Only if it is during a reconfigure: on the Studer-Innotec integration page could you please press 'download diagnostics' and post the resulting file here as attachment (or email to: info at anko dot co dot nz)
4. If I would modify one of the integration's files to add lots of extra tracing, would you be able to manually copy that to your system and do a test?

possibly more questions to come...

**Comment by Duncik** [comment]
Hello. I have tried to add integration into other Homeassistant instance (no studer in network) but all worked as expected. Got after the search and got error while connecting. So i think that instance with studer is just broken.   I will try to go there by the end of the year and try to make fresh install and add integration to it. Now it sometimes crashes and overall acts weird. I am very thankful for your help and will let you know after i reinstall. Dont want to waste your time if problem can be on my end.

**Comment by ankohanse** [comment]
I've attached a modified config_flow.py file that has a lot of extra tracing to see what it going on.
Could you please give that a try? Note that you will need to restart HA after you have copied the file and before you run your test.

[config_flow.zip](https://github.com/user-attachments/files/18235333/config_flow.zip)

**Comment by Duncik** [comment]
----------------------------------------------------------------------------
Studer Xcom
Domain: studer_xcom
----------------------------------------------------------------------------
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - start config flow
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default voltage=240 Vac
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default port=4001
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default user_level=BASIC
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default webconfig_url=None
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default devices=[]
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - default polling_interval=30
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - next step discover Moxa
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - prepare tasks for phase MOXA_DISCOVER
2024-12-24 14:20:18.540 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - create task xcom_webconfig, phase=MOXA_DISCOVER, idx=0
2024-12-24 14:20:18.540 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discover Xcom Moxa Web Config
2024-12-24 14:20:20.560 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet
2024-12-24 14:20:20.560 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0
2024-12-24 14:20:20.560 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step user - resulting flowresult = {'type': <FlowResultType.SHOW_PROGRESS: 'progress'>, 'flow_id': '01JFWD6M1Y0XHP1QW9PYKV88V9', 'handler': 'studer_xcom', 'progress_action': 'xcom_webconfig', 'description_placeholders': {'percent': '0%'}, 'progress_task': <Task pending name='Task-907' coro=<ConfigFlowHandler._async_xcom_webconfig() running at /config/custom_components/studer_xcom/config_flow.py:355> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>, 'step_id': 'progress'}
2024-12-24 14:20:20.561 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.127.254
2024-12-24 14:20:20.562 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.41
2024-12-24 14:20:20.563 INFO (MainThread) [aioxcom.xcom_discover] trying http://172.30.232.2
2024-12-24 14:20:20.565 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.22
2024-12-24 14:20:20.566 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.10
2024-12-24 14:20:20.566 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.1
2024-12-24 14:20:20.567 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.46
2024-12-24 14:20:20.568 INFO (MainThread) [aioxcom.xcom_discover] trying http://192.168.1.2
2024-12-24 14:20:20.584 INFO (MainThread) [aioxcom.xcom_discover] Found Moxa Web Config url: http://192.168.1.10
2024-12-24 14:20:20.585 INFO (MainThread) [custom_components.studer_xcom.config_flow] Discovered Xcom Moxa Web Config at http://192.168.1.10
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Discover Xcom Moxa Web Config - return to flow
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig not done yet
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show progress, action:xcom_webconfig, percent:0
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Discover Xcom Moxa Web Config - done
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - task xcom_webconfig done
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - done, phase=MOXA_DISCOVER
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - show done, next step configure client
2024-12-24 14:20:20.585 DEBUG (MainThread) [custom_components.studer_xcom.config_flow] Step progress - next step 

![Screenshot 2024-12-24 142222](https://github.com/user-attachments/assets/782896b2-964a-45ad-9b0f-c62593841cb1)
configure client

**Comment by ankohanse** [comment]
Unfortunately I was not able to discover the source of the problem using the additional info in your latest trace. All values and the order of traces are as I expect them. Last trace is just before I hand back control to HA when Moxa discovery step is done, and would expect to HA hand control back to display the next step's dialog. But that never happens.

Question: is the system that has this problem regularly updated, or could it possibly still be running an older version of HA core?
There is one similar issue report I found for progress steps, and that issue was solved somewhere in 2023. 
See [Data entry flow with several Show Progress steps only executes first step #95749](https://github.com/home-assistant/core/issues/95749)

**Comment by Jmayormayu** [comment]
Hi, 
@ankohanse thank you so much for this development for Studer owner. Great great job ! 

FYI I encountered same problem when I first installed your add-on. I was using nabu casa cloud connection. Changing to local network access solved my problem. 
Wheb I reconfigure the Studer add-on I sometimes need to restart the process 1-3 times to get unstuck from “searching xcom Moxa …”

**Comment by Duncik** [comment]
That can be it ! I am trying to configure it via cloud. Will try it locally ! Thanks for the recommendation :-).

**Comment by ankohanse** [comment]
I will add a note to the documentation and possibly even in the screen itself to make sure users only try to setup using local connection

**Comment by Duncik** [comment]
Hello i have tried it locally and indeed there is progress. But still not working sadly. I will attach log file for reference. 
[home-assistant_2025-01-06T14-49-20.399Z.log.txt](https://github.com/user-attachments/files/18320825/home-assistant_2025-01-06T14-49-20.399Z.log.txt)
![SmartSelect_20250106_154708_Chrome](https://github.com/user-attachments/assets/d6672291-ddd8-4238-a762-a437d30f0178)

**Comment by ankohanse** [comment]
@Duncik 
This seems to be an unrelated issue. In the trace I can see that the configuration succeeded in doing the Moxa Web Config discovery where others got stuck and has progressed to displaying the voltage and port dialog.

I've created a separate bug report for what you encountered here: #16

**Comment by ankohanse** [comment]
@Duncik 
Additional note: it seems that it is not necessary to run the configuration of the integration on a web browser on the Home Assistant device itself (like you did by installinng the Firefox Add-on).

It should be sufficient to just open a web-browser to homeassistant.local:8123 on any computer in the local network. I.e. on a computer within the same network as where Home Assistant is connected to and where the Studer Xcom device is connected to.

**Comment by Duncik** [comment]
I am helping a friend who is not very tech savvy. And dont want to bother him unless its necessary . Even then i better drive to him for a visit :-) . That is why i am preferably using NabuCasa cloud and firefox addon . 
Also was able to configure Moxa via that firefox addon which seems amazing as well. I also made sure that settings are correct (moxa has IP of HASS) do you think it would help to use some other port ?
Btw thank you a lot for yours support. Its really amazing !

**Comment by Duncik** [comment]
This was solved by not configuring the integration via NabuCasa cloud but locally. 
Thank you a lot for support and have a great day !
